apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: secret_username
      valueFrom:
        secretKeyRef:
          name: secretkeyref
          key: username
    - name: secret_password
      valueFrom:
        secretKeyRef:
          name: secretkeyref
          key: password
