apiVersion: v1
kind: Pod
metadata:
  name: kuard-amd64
spec:
  containers:
  - name: kuard-amd64
    image: gcr.io/kuar-demo/kuard-amd64:1
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8080
    volumeMounts:
    - name: data
      mountPath: /var/lib/app
  volumes:
  - name: data
    hostPath:
      path: /var/lib/app
