apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  env: configmap_param
  volume: config_volume
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: redis
    image: redis
    envFrom:
    - configMapRef:
        name: redis-config
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: redis-config
